apiVersion: apps/v1
kind: Deployment
metadata:
  name: snattest
  labels:
    app: snat-test
spec:
  replicas: 6
  selector:
    matchLabels:
      app: snat-test 
  template:
    metadata:
      labels:
        app: snat-test
    spec:
      containers:
      - name: snat-test
        image: qkeastus.azurecr.io/demo/snat-test:latest
        imagePullPolicy: Always
        env:
        - name: JAVA_OPTS
          value: "-Xmx200m"
        - name: logLevel
          value: FINE
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "400Mi"
            cpu: "400m"